# Generated by Django 2.2.1 on 2019-06-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transport',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
