# Generated by Django 2.2.1 on 2019-06-08 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportstep',
            name='project',
        ),
        migrations.AlterField(
            model_name='transportstep',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.Transport'),
        ),
        migrations.CreateModel(
            name='TransportWaypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Address')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='core.Transport')),
            ],
            options={
                'ordering': ('order',),
                'unique_together': {('transport', 'order')},
            },
        ),
    ]
