# Generated by Django 2.2.1 on 2019-06-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190608_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='mode',
            field=models.CharField(choices=[('guess', 'Guess'), ('plane', 'Plane'), ('car', 'Car'), ('train', 'Train'), ('truck', 'Truck'), ('bus', 'Bus'), ('foot', 'Foot')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transportstep',
            name='mode',
            field=models.CharField(choices=[('guess', 'Guess'), ('plane', 'Plane'), ('car', 'Car'), ('train', 'Train'), ('truck', 'Truck'), ('bus', 'Bus'), ('foot', 'Foot')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='TransportMode',
        ),
    ]
