# Generated by Django 2.2.1 on 2019-06-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190608_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ends_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='starts_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
