# Generated by Django 2.2.1 on 2019-06-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190609_2043'),
        ('core', '0003_auto_20190609_1909'),
    ]

    operations = [
    ]
