# Generated by Django 2.2.1 on 2019-08-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0003_auto_20190714_2203")]

    operations = [
        migrations.AddField(
            model_name="address",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new", "New"),
                    ("unknown", "Unknown"),
                    ("geocoded", "Geocoded"),
                ],
                default="new",
                max_length=10,
                null=True,
                verbose_name="Status",
            ),
        )
    ]
