# Generated by Django 2.2.1 on 2019-08-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_activeplugins'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeplugins',
            name='slug',
            field=models.CharField(default=1, max_length=200, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
