# Generated by Django 2.2.1 on 2019-08-12 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0006_activeplugins_slug")]

    operations = [
        migrations.RenameField(
            model_name="activeplugins", old_name="settings", new_name="config"
        )
    ]
