# Generated by Django 2.2.1 on 2019-08-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0008_auto_20190828_1533")]

    operations = [
        migrations.AddField(
            model_name="activeplugin",
            name="enabled",
            field=models.BooleanField(default=True),
        )
    ]
