# Generated by Django 2.2.1 on 2019-08-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0009_activeplugin_enabled")]

    operations = [
        migrations.RemoveField(model_name="report", name="config"),
        migrations.AddField(
            model_name="report",
            name="theme_config",
            field=models.TextField(
                blank=True, null=True, verbose_name="Theme config JSON"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="theme_slug",
            field=models.CharField(
                default="", max_length=200, verbose_name="Theme slug"
            ),
            preserve_default=False,
        ),
    ]
