# Generated by Django 2.2.1 on 2019-08-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0010_auto_20190831_1021")]

    operations = [
        migrations.AddField(
            model_name="activeplugin",
            name="type",
            field=models.CharField(default="", max_length=50, verbose_name="Type"),
            preserve_default=False,
        )
    ]
